# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    
    - task: DenoDownload@1
      displayName: Download Deno
      inputs:
        version: 1.2.2

    - task: CmdLine@2
      displayName: Run Tests
      inputs:
        script: |
          echo running tests...
          deno test
    
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        containerRegistry: dockerHubServiceConnection
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile.prod'
        repository: colinknebl/api
        tags: |
          1
          latest