# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection1
        
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.prod'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(dockerHub)
        # repository: 
        repository: colinknebl/api
        command: push
        tags: |
          1
          test1
          test2