FROM colinknebl/deno:1.2.2

# Set the working director to /app
WORKDIR /app

# Copy the src code to /app
COPY src/ .

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache main.ts

# The port that your application listens to.
EXPOSE 1991

# Start the app
CMD ["deno", "run", "--allow-net", "/app/main.ts"]