FROM colinknebl/denon:2.3.0

# Expose the /app dir for mounting
VOLUME /app

# Set the working director to /app
WORKDIR /app

# The port that your application listens to.
EXPOSE 1991

# Start the app
CMD ["denon", "run", "--allow-net", "/app/main.ts"]