FROM ubuntu:latest

# update ubuntu
RUN apt-get update

# install deps required to install deno
RUN apt-get install -y apt-utils curl zip unzip

# install deno
RUN curl -fsSL https://deno.land/x/install/install.sh | sh

# Add deno to PATH
ENV DENO_INSTALL="/root/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"

# install denon, the nodemod for deno
RUN deno install --allow-read --allow-run --allow-write --allow-net -f --unstable https://deno.land/x/denon@2.3.0/denon.ts

# Cache the dependencies
COPY deps.ts .
RUN deno cache deps.ts

# The port that your application listens to.
EXPOSE 1991

# Expose the /app dir for mounting
VOLUME /app

WORKDIR /app

COPY src/ .

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache /app/main.ts

CMD ["denon", "run", "--allow-net", "/app/main.ts"]